baseurl = "http://anthonymcook.com"
languageCode = "en-us"
title = "digital. [nomad]"

MetaDataFormat = "yaml"
editor = "vim"

SectionPagesMenu = "section"

[params]
sidebartitle = "digital. [nomad]"
sidebartagline = "the digital frontier"
